/** Single source of truth for registered MCP tool names (sorted). */
export const EXPECTED_TOOLS = [
  "apply_patch",
  "check_image_dependencies",
  "check_system",
  "check_url",
  "check_workspace",
  "chrome_load_extension",
  "collect_debug_bundle",
  "delete_workspace_file",
  "fetch_url",
  "git_add",
  "git_commit",
  "git_init",
  "git_status",
  "image_adjust",
  "image_batch",
  "image_composite",
  "image_crop",
  "image_info",
  "image_ocr",
  "image_remove_background",
  "image_resize",
  "image_rounded",
  "image_text",
  "image_upscale",
  "image_upscale_ai",
  "list_scripts",
  "list_workspace_tree",
  "move_workspace_file",
  "read_lints",
  "read_project_info",
  "read_workspace_file",
  "run_coding_session",
  "run_project_script",
  "run_safe_command",
  "search_web",
  "search_workspace",
  "write_workspace_file",
] as const;

export const EXPECTED_TOOL_COUNT = EXPECTED_TOOLS.length;

export type RegisteredToolName = (typeof EXPECTED_TOOLS)[number];
